exclude_paths:
  - "lib/tasks/cucumber.rake"
  - "script/cucumber"
  - "test/"

plugins:
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
