plugins:
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

exclude_patterns:
  - 'bin/'
  - 'db/'
  - 'lib/assets/'
  - 'lib/tasks/'
  - 'scripts/cucumber'
  - 'tests/'
