language: ruby
cache: bundler

rvm:
  - 2.4.0

services:
  - mysql

before_script:
  - 'bundle install'
  - "RAILS_ENV='test' bundle db:setup"

script: 'bundle exec cucumber'

branches:
  only:
    - development
